### ISSUE TITLE
error acessing dubbed animes

### ISSUE THREAD

**Issue by N4v41** [destruc7i0n/nani#22]
when i try to acess animes that are dubbed i cant acces them from nani
![image](https://user-images.githubusercontent.com/45365461/66969431-d9e91000-f05f-11e9-86e6-400733174a32.png)

**Comment by destruc7i0n** [comment]
For some reason Crunchyroll makes the videos visible to the rest of the world even though nobody can watch it... There's not fix for this other than to use a VPN.

**Comment by N4v41** [comment]
ok, thanks!
