### ISSUE TITLE
It's possible that certain titles will be impossible to search for

### ISSUE THREAD

**Issue by zlmonroe** [destruc7i0n/nani#24]
If you search for a show which has a short name that is contained in other shows, you can have the show not come up in the search after typing the entire name. For example, the show "Magi" pulls up "A Certain Magical Index", "Akashic Records of a Bastard Magic Instructor", "Anti-Magic Academy: The 35th Test Platoon", "Isekai Cheat Magician", and "Knight’s & Magic" by the time you have typed the whole title.

**Comment by destruc7i0n** [comment]
Seems that I forgot to turn on notifications for this repo 😬
Fixed this problem, added a scrollbar to not make the list get too long
