### ISSUE TITLE
Can't play some videos

### ISSUE THREAD

**Issue by DarkstaIkers** [destruc7i0n/nani#29]
When CR gives the url pl.crunchyroll.com videos can't be played, it's like it has a CORS in this url.

**Comment by destruc7i0n** [comment]
Can you provide some such links?

**Comment by DarkstaIkers** [comment]
Yes, I do. This one https://nani.ninja/series/246948/796445

**Comment by destruc7i0n** [comment]
Hmm you're right, they do seem to be adding CORS to their URLs sometimes. After reloading a couple of times I was able to get a non CORS url, though. Seems to be a slow release for this so I'll need to look into solutions for how to get around. Probably a chrome extension or the like.

**Comment by destruc7i0n** [comment]
I pushed a small fix for now which uses a proxy to bypass the pl.crunchyroll.com request, since that is the only one which seems to have CORS enabled. Hopefully this should be enough for now.

**Comment by py7hon** [comment]
> I pushed a small fix for now which uses a proxy to bypass the `pl.crunchyroll.com` request, since that is the only one which seems to have CORS enabled. Hopefully this should be enough for now.

have you tried replacing `pl.crunchyroll.com` with `dl.v.vrv.co` and `a-vrv.akamaized.net` for bypassing CORS

**Comment by destruc7i0n** [comment]
Oh hmm they now seem to be blocking just about every request with CORS, future doesn't look too good for this project now. Not sure how many would want to download a client or use a plugin

**Comment by destruc7i0n** [comment]
Seems like it is possible to easily proxy the deeper playlist CORS requests, fixed now!
