### ISSUE TITLE
Issue when production build but no when using dev build

### ISSUE THREAD

**Issue by phantomtnt** [destruc7i0n/nani#32]
Hello, i've cloned this and i was trying to make it work in local, the only problem i found is that when i create the production build and access the page i cannot play videos i get the error in the image.
![imagen](https://user-images.githubusercontent.com/2342312/110470220-981f9600-80a8-11eb-90e7-285408dfe36f.png)

but when i use development build, it works perfect, ¿what could be the issue in the production build?

thanks!

**Comment by destruc7i0n** [comment]
Ah, there is a proxy to get around the CORS requests of the videos. My hosted version has this setup but other versions would need to configure that. If you want to try disabling it you can comment out the lines here https://github.com/destruc7i0n/nani/blob/master/src/components/Player/Player.js#L55-L56

**Comment by phantomtnt** [comment]
Yes i tried that, and worked, thanks!!
