### ISSUE TITLE
Method to automatically update the Key-Pair-Id ?

### ISSUE THREAD

**Issue by agmvw** [destruc7i0n/nani#35]
Hi, I don't have much advanced knowledge, I'm just experimenting and reviewing methods by trial and error, but I can understand a little bit and I see that your site nani.ninja, somehow automatically updates the 'https://pl.crunchyroll.com/evs2/61ee4...' links.
I would like to know how I can do this, to redirect the chapters to my personal site, and not update one by one manually
example of full URL that I usually get:
`https://fuckcors.app/https://pl.crunchyroll.com/evs2/827eac49c32d0b6804fcb897a11aa1d7/assets/51fbd059df8fefdfdca59d66dc145481_3858413.mp4/index-v1-a1.m3u8?Expires=1648310986&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMi84MjdlYWM0OWMzMmQwYjY4MDRmY2I4OTdhMTFhYTFkNy9hc3NldHMvNTFmYmQwNTlkZjhmZWZkZmRjYTU5ZDY2ZGMxNDU0ODFfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDgzMTA5ODZ9fX1dfQ__&Signature=Z0Je6q-LHn1IXXWJeeGOoe8NJGgjCH34BlMNM91Y83nnrctKYLf9FNHoFV0mud~5ajl~Ja1QlaQQ06MRG6IkBDHa0MhW~fumYOuptvV3hNpGQLYzwmlTPVK1exyoX9dGEfIJ9cFC2P8oK4TwmyvNha9BYkY72gfERrMaTBgjGZ2VwetSdkU9MNRNFkL6Wy1fEmWXfW8KdLWKk9XH-HD3f52eKn3V0g3qhCXpGExVY4g0WENKhKdnuvCHoHFOr9bqOsWtgn1Lqzudq~0GZUUvxvREBSwOuSOl~Ou6jjlSHi0euY8ND4R7X8phbcHhL~EKdv1sKHNz60RluXDntKLYHg__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=fy-prod`

this section never changes: `https://pl.crunchyroll.com/evs2/827eac49c32d0b6804fcb897a11aa1d7/assets/51fbd059df8fefdfdca59d66dc145481_3858413.mp4/index-v1-a1.m3u8?Expires=`

and this is where it constantly generates new sets of codes:
`1648310986&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMi84MjdlYWM0OWMzMmQwYjY4MDRmY2I4OTdhMTFhYTFkNy9hc3NldHMvNTFmYmQwNTlkZjhmZWZkZmRjYTU5ZDY2ZGMxNDU0ODFfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDgzMTA5ODZ9fX1dfQ__&Signature=Z0Je6q-LHn1IXXWJeeGOoe8NJGgjCH34BlMNM91Y83nnrctKYLf9FNHoFV0mud~5ajl~Ja1QlaQQ06MRG6IkBDHa0MhW~fumYOuptvV3hNpGQLYzwmlTPVK1exyoX9dGEfIJ9cFC2P8oK4TwmyvNha9BYkY72gfERrMaTBgjGZ2VwetSdkU9MNRNFkL6Wy1fEmWXfW8KdLWKk9XH-HD3f52eKn3V0g3qhCXpGExVY4g0WENKhKdnuvCHoHFOr9bqOsWtgn1Lqzudq~0GZUUvxvREBSwOuSOl~Ou6jjlSHi0euY8ND4R7X8phbcHhL~EKdv1sKHNz60RluXDntKLYHg__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=fy-prod`

I would like to know which method you use, or advise me on an alternative.
pd: For now if I can see the videos on my web page, but they expire after a short time...
capture: https://i.imgur.com/6SWYU5k.jpg

**Comment by destruc7i0n** [comment]
I do not know of any method to bypass the policies
