### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by DarkstaIkers** [destruc7i0n/nani#38]
It seems CR did apply a CORS in the urls.

**Comment by destruc7i0n** [comment]
Yep, it does seem like they did do that recently. Probably came with the new design they rolled out everywhere? I could proxy every request but that would add some latency to streaming and could also get my server account banned (DMCA, has happened twice to me already from this project) so I will probably not take that route.. 
With the new design fixing most of the gripes I had with CR (specifically their flash player and ancient design) I don't see much of a need for this project personally, unless there are other use-cases I am unaware of?
